#!/usr/bin/env bash
# Transfers a file through SCP
if [ "$#" -le 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3@$2:~/." -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
fi
