#!/usr/bin/env bash
# Installs and activates an nginx server
apt-get update
apt-get -y install nginx
rule="server_name _;\n	rewrite \^\/redirect_me\$ https:\/\/www.youtube.com\/watch=?v=QH2-TGUlwu4 permanent;"
sed -i \
	"s/server_name _;/${rule}/g" \
	/etc/nginx/sites-enabled/default 
service nginx restart

