#!/usr/bin/env bash
# Installs and activates an nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
rule="	rewrite ^/redirect_me/?(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "45 i ${rule}" /etc/nginx/sites-enabled/default 
echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo service nginx restart
