#!/usr/bin/env bash
# Installs and configurates HAproxy
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

rule='
frontend lb
        bind *:80
        default_backend nodes
        option forwardfor

backend nodes
        balance roundrobin
        server 941-web-01 35.237.10.249:80
        server 941-web-02 35.237.191.203:80'

printf "%s" "$rule" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
