#!/usr/bin/env bash
# Sets nginx default site to listen to port 80.
sed -i "s/listen 8080 default_server/listen 80 default_server/i" /etc/nginx/sites-enabled/default
sed -i "s/listen [::]:80 default_server/listen [::]:80 default_server/i" /etc/nginx/sites-enabled/default

service nginx restart
