#!/usr/bin/env bash
# Creates a daemon that prints "I am alive!" to /tmp/my_process every two seconds
if [ "$#" -ne 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

if [[ $1 == "start" ]]
then
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"

elif [[ $1 == "stop" ]]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [[ $1 == "restart" ]]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi
