#!/usr/bin/env bash
# This script prints "Holberton School" ten times, prints "bad luck" instead in the 4th iteration
# and prints "good luck" instead in the 8th iteration.
i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	i=$((i+1))
done


