#!/usr/bin/env bash
# Displays the hours from 0 to 12 and the minutes from 1 to 59.
i=0
while [ $i -le 12 ]
do
	j=1
	echo "Hour: $i"
	while [ $j -le 59 ]
	do
		echo "$j"
		j=$((j+1))
	done
	i=$((i+1))
done




