#!/usr/bin/env bash
# Checks if file exists and prints some basic information.
if [ -e "$1" ]
then
	echo "$1 file exists"
	if [ -s "$1" ]
	then
		echo "$1 file is not empty"
	else
		echo "$1 file is empty"
	fi
	if [ ! -d "$1" ]
	then
		echo "$1 is a regular file"
	fi
else
	echo "$1 file does not exist"
fi
